on:
  push:
    branches: master
  pull_request:
    branches: master

name: unittest

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        
        - name: Set up Python version
          uses: actions/setup-python@v2.2.2
          with:
            python-version: 3.9.9
            cache: 'pip'

        - name: Create and start virtual environment
          run: |
            python -m venv venv
            source venv/bin/activate

        - name: Install unittest
          run: pip install unittest2

        - name: Test with unittest
          run: |
            unittest /home/runner/work/unittest/tests
